config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :articles do
    resources :comments
  end
  resources :users
  
  get 'simple_pages/index'

  get 'simple_pages/about'

  get 'simple_pages/contact'

  root 'articles#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  
    user ||= User.new #guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :manage, User, id: user.id
    end
  
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments

	def average_rating
       comments.average(:rating).to_f
    end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates :body, presence: true
  validates :user, presence: true
  validates :article, presence: true
  validates :rating, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
  redirect_to main_app.root_url, alert: exception.message
end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! , except: %i[index show]
  #load_and_authorize_resource except: %i[index show]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all.paginate(:page => params[:page], :per_page => 3)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @comments = @article.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :image_url)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
	   @article = Article.find(params[:article_id])
       @comment = @article.comments.new(comment_params)
       @comment.user = current_user
       respond_to do |format|
      if @comment.save
        format.html { redirect_to @article, notice: 'Review was created successfully.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { redirect_to @article, alert: 'Review was not saved successfully.' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
  	@comment = Comment.find(params[:id])
    article = @comment.article
    @comment.destroy
    redirect_to article

  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :body, :rating)
  end
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! , except: %i[index]
  load_and_authorize_resource except: %i[index]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_comments.html.erb
<div class="article-reviews">
    <% @comments.each do |comment| %>
        <div class="row">
            <hr>
            <p>
    <%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
    <% if signed_in? && current_user.admin? %>
        <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, article_comment_path(comment.article, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
</p>

            <div class="rated" data-score="<%= comment.rating %>"></div>
            <p><%= comment.body %></p>

        </div>
    <% end %>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :article_title %>
  </div>
  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :article_image %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :article_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/_new_comment.html.erb
<% if signed_in? %>
  <h4 class="add-review">Add a review:</h4>
  <%= form_for([@article, @article.comments.build], remote: true) do |f| %>
    
    <div class="form-group">
    <%= f.label :body, "Comments", class: 'form-label' %>
    <%= f.text_area :body, class: 'form-control', :required => true, title: "Leave your comments(required)" %>
  </div>
    
    <div class="rating"></div>
   
    <div class="actions">
    <%= f.submit "Submit", class: 'btn btn-primary'%>
  </div>
  <% end %>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<section class="container-fluid" id="showing-articles">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
           
            <% @articles.each_with_index do |article, index| %>
            <li data-target="#carousel-example-generic" data-slide-to="<%= index %>" class="<%= " active" if article == @articles.first %>">
                
            </li>
            <% end %>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <% @articles.each do |article| %>
            <div class="item<%= " active" if article == @articles.first %>">
                <%= link_to image_tag(article.image_url), article %>
                <div class="carousel-caption">
                    <h3><%= article.title %></h3>
                </div>
            </div>
            <% end %>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</section>

<section class="container">

  <div class="header">
    <h1>IBTE Blog - Foof is Magic</h1>
  </div>

  <div class="row">
    <% @articles.each do |article| %>
      <div class="col-md-4 col-sm-6 article-box">
        <a href="/articles/<%= article.id %>"><%= image_tag article.image_url, class: "img-responsive", alt: "article image"%></a>
          <a href="/articles/<%= article.id %>"><h3 class="article-title"><%= article.title %></h3></a>
          <p class="article-body"><%= article.body %></p>
          <% if signed_in? %>
            <%= link_to 'Edit', edit_article_path(article) %>
            <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
      </div>
    <% end %>
    <%= will_paginate @articles %>
  </div>
  <% if signed_in? %>
    <%= link_to 'New Article', new_article_path %>
  <% end %>
</section>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<section class="container">
	<div class="row article">
		<div class="col-sm-6 col-xs-12">
			<%= image_tag @article.image_url, class: "img-responsive", alt: "article image"%>
		</div>
		<div class="col-sm-6 col-xs-12">
			<div class="article-content">
				<h3 class="show-article-title"><%= @article.title %></h3>
          		<p class="article-body"><%= @article.body %> <a href="#">Read more</a></p>
          		<p>Average Rating: <div class="rated" data-score="<%= @article.average_rating %>"></div> </p>

          		<%= render 'new_comment' %>
          		<%= render 'comments' %>
          		<%= will_paginate @comments %>
			</div>
		</div>
	</div>
</section>

<% if user_signed_in? %>
 <%= link_to 'Edit', edit_article_path(@article) %> |
<% end %>

<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IBTI Blog</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Pacifico">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Itim">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Spirax">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cookie">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>

  <body>
  	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "IBTE Blog", root_path, class: "navbar-brand" %> <!--end projectName -->
            </div> <!--end navbar-header -->
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-left">
                    <li><%= link_to 'About Us', simple_pages_about_path %></li>
                    <li><%= link_to 'Contact US', simple_pages_contact_path %></li>
                    <li><%= link_to 'Articles', articles_path %></li>
                </ul>
                <ul class="nav navbar-nav pull-right">
                    <li>
                       <% if user_signed_in? %>
                        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
                       <% else %>
                        <%= link_to('Login', new_user_session_path) %>
                       <% end %>
                    </li>
                </ul>
                
            </div> <!-- end navbar-collaps -->
        </div> <!-- end nav container-->
    </nav>

    <!-- Flash Notice Tags -->
    <% if notice %>
      <div id="notice" class="alert alert-success"><%= notice %></div>
    <% end %>
    <% if alert %>
      <div id="alert" class="alert alert-danger"><%= alert %></div>
    <% end %>

    <%= yield %>

    <footer class="site-footer">
        Copyright &copy; 2017 Ibtesam DH
    </footer>


<script type="text/javascript">
     $('.rating').raty({
    starHalf: '<%= asset_path 'star-half.png' %>',
    starOff: '<%= asset_path 'star-off.png' %>',
    starOn: '<%= asset_path 'star-on.png' %>',
    scoreName: 'comment[rating]'
  });
  $('.rated').raty({
    starHalf: '<%= asset_path 'star-half.png' %>',
    starOff: '<%= asset_path 'star-off.png' %>',
    starOn: '<%= asset_path 'star-on.png' %>',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
  
</script>
  </body>
</html>

app/views/simple_pages/about.html.erb
<section id="about">
    <div class="header">
        <h1>About US</h1>
        <p>You want to learn cooking ! we are here to help you to become a master chef !! </p>
    </div>
</section>

app/views/simple_pages/contact.html.erb
<section class="container-fluid">
	<div class="jumbotron">
		<div class="row centered">
			<div class="col-sm-6 personalize">
          		<h2>Where to find us</h2>
          		<p>We operate from a lovely office in the heart of Gaza.</p>
        	</div>
        	<div class="col-sm-6 contact-form">
          		<%= form_with(url: "/static_pages/thank_you", local: true) do |form| %>

        			<div class="form-group">
          				<%= form.label :name, class: 'form-label' %>
          				<%= form.text_field :name, class: "form-control", placeholder: "Your Name", :required => true, title: 'Please fill your name here'%>
        			</div>  

        			<div class="form-group">
          				<%= form.label :email, "Email Address", class: 'form-label' %>
          				<%= form.text_field :email, class: "form-control", placeholder: "Your Email", type:"email", :required => true, title: "required (example@hotmail.com)" %>
        			</div>

        			<div class="form-group">
          				<%= form.label :message, class: 'form-label' %>
          				<%= form.text_area :message, class: "form-control", placeholder: "Your Message", :required => true, title: "Fill a message (required)" %>
        			</div>

        			<div class="actions">
            			<%= form.submit "Send Us a Message", class: 'btn btn-primary' %>   
        			</div>

      			<% end %>
        	</div>
        	<div class="col-sm-6 contact-touch">
          		<h2>Stay in touch!</h2>
          		<p>Follow us on our social media channels.</p>
          		<ul class="list-inline social-media">
          			<li><a href="#" style="color: #286090"><i class="fa fa-facebook-square" aria-hidden="true"></a></i></li>
          			<li><a href="#" style="color: #286090"><i class="fa fa-twitter-square" aria-hidden="true"></i></a></li>
          			<li><a href="#" style="color: #286090"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></li>
      			</ul>
        	</div>
  		</div>
	</div>
</section>

app/views/simple_pages/index.html.erb
<h1>SimplePages#index</h1>
<p>Find me in app/views/simple_pages/index.html.erb</p>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :user_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :user_last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>